import React from 'react';
import { screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../App';
import renderWithRouter from './RenderWithRouter';

describe('Testa o componente Pokedex.js', () => {
  it('deveria exibir um <h2> com o texto Encountered pokémons', () => {
    renderWithRouter(<App />);
    const Header = screen.getByRole('heading', { name: 'Encountered pokémons' });
    expect(Header).toBeInTheDocument();
  });

  it('deveria exibir o próximo pokemon quando o botão fosse clicado', () => {
    renderWithRouter(<App />);
    const NextBtn = screen.getByRole('button', { name: 'Próximo pokémon' });
    expect(NextBtn).toBeInTheDocument();
    const AllBtn = screen.getByRole('button', { name: 'All' });
    expect(AllBtn).toBeInTheDocument();
    const AllBtn2 = screen.getAllByTestId('pokemon-type-button');
    expect(AllBtn2[0]).toBeInTheDocument();
    userEvent.click(AllBtn);
    const firstPoke = screen.getByText('Pikachu');
    expect(firstPoke).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke2 = screen.getByText('Charmander');
    expect(Poke2).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke3 = screen.getByText('Caterpie');
    expect(Poke3).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke4 = screen.getByText('Ekans');
    expect(Poke4).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke5 = screen.getByText('Alakazam');
    expect(Poke5).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke6 = screen.getByText('Mew');
    expect(Poke6).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke7 = screen.getByText('Rapidash');
    expect(Poke7).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke8 = screen.getByText('Snorlax');
    expect(Poke8).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Poke9 = screen.getByText('Dragonair');
    expect(Poke9).toBeInTheDocument();
    userEvent.click(NextBtn);
    expect(firstPoke).toBeInTheDocument();
  });

  it('deveria exibir os botôes de tipo e mostrar somente os pokes do tipo', () => {
    renderWithRouter(<App />);
    const NextBtn = screen.getByRole('button', { name: 'Próximo pokémon' });
    expect(NextBtn).toBeInTheDocument();
    const AllBtn = screen.getByRole('button', { name: 'All' });
    expect(AllBtn).toBeInTheDocument();
    const ElectricBtn = screen.getByRole('button', { name: 'Electric' });
    expect(ElectricBtn).toBeInTheDocument();
    userEvent.click(ElectricBtn);
    const Pikachu = screen.getByText('Pikachu');
    expect(Pikachu).toBeInTheDocument();
    const FireBtn = screen.getByRole('button', { name: 'Fire' });
    expect(FireBtn).toBeInTheDocument();
    userEvent.click(FireBtn);
    const Fire1 = screen.getByText('Charmander');
    expect(Fire1).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Fire2 = screen.getByText('Rapidash');
    expect(Fire2).toBeInTheDocument();
    const BugBtn = screen.getByRole('button', { name: 'Bug' });
    expect(BugBtn).toBeInTheDocument();
    userEvent.click(BugBtn);
    const Bug = screen.getByText('Caterpie');
    expect(Bug).toBeInTheDocument();
    const PoisonBtn = screen.getByRole('button', { name: 'Poison' });
    expect(PoisonBtn).toBeInTheDocument();
    userEvent.click(PoisonBtn);
    const Poison = screen.getByText('Ekans');
    expect(Poison).toBeInTheDocument();
    const PsychicBtn = screen.getByRole('button', { name: 'Psychic' });
    expect(PsychicBtn).toBeInTheDocument();
    userEvent.click(PsychicBtn);
    const Psychic1 = screen.getByText('Alakazam');
    expect(Psychic1).toBeInTheDocument();
    userEvent.click(NextBtn);
    const Psychic2 = screen.getByText('Mew');
    expect(Psychic2).toBeInTheDocument();
    const NormalBtn = screen.getByRole('button', { name: 'Normal' });
    expect(NormalBtn).toBeInTheDocument();
    userEvent.click(NormalBtn);
    const Normal = screen.getByText('Snorlax');
    expect(Normal).toBeInTheDocument();
    const DragonBtn = screen.getByRole('button', { name: 'Dragon' });
    expect(DragonBtn).toBeInTheDocument();
    userEvent.click(DragonBtn);
    const Dragon = screen.getByText('Dragonair');
    expect(Dragon).toBeInTheDocument();
  });
});
